export const DEFAULT_CURRICULUM = [
  {
    name: 'Practical Life', icon: '🏠', color: '#F59E0B', sequence: 1,
    description: 'Activities that develop independence, coordination, concentration, and order',
    activities: [
      { name: 'Carrying a tray',           level: 'casa', sequence: 1 },
      { name: 'Pouring — dry (beans)',      level: 'casa', sequence: 2 },
      { name: 'Pouring — liquid (water)',   level: 'casa', sequence: 3 },
      { name: 'Spooning',                   level: 'casa', sequence: 4 },
      { name: 'Tweezers / tongs',           level: 'casa', sequence: 5 },
      { name: 'Folding cloth',              level: 'casa', sequence: 6 },
      { name: 'Sweeping',                   level: 'casa', sequence: 7 },
      { name: 'Dusting',                    level: 'casa', sequence: 8 },
      { name: 'Table washing',              level: 'casa', sequence: 9 },
      { name: 'Dressing frame — large button', level: 'casa', sequence: 10 },
      { name: 'Dressing frame — small button', level: 'casa', sequence: 11 },
      { name: 'Dressing frame — zip',       level: 'casa', sequence: 12 },
      { name: 'Dressing frame — snap',      level: 'casa', sequence: 13 },
      { name: 'Dressing frame — buckle',    level: 'casa', sequence: 14 },
      { name: 'Dressing frame — lace & bow',level: 'casa', sequence: 15 },
      { name: 'Plant care — watering',      level: 'casa', sequence: 16 },
      { name: 'Food preparation — banana',  level: 'casa', sequence: 17 },
    ],
  },
  {
    name: 'Sensorial', icon: '🎨', color: '#EF4444', sequence: 2,
    description: 'Materials that refine and develop the senses, isolating one quality at a time',
    activities: [
      { name: 'Pink Tower',              level: 'casa', sequence: 1 },
      { name: 'Brown Stair',             level: 'casa', sequence: 2 },
      { name: 'Red Rods',                level: 'casa', sequence: 3 },
      { name: 'Cylinder Blocks (set 1)', level: 'casa', sequence: 4 },
      { name: 'Cylinder Blocks (set 2)', level: 'casa', sequence: 5 },
      { name: 'Cylinder Blocks (set 3)', level: 'casa', sequence: 6 },
      { name: 'Cylinder Blocks (set 4)', level: 'casa', sequence: 7 },
      { name: 'Colour Tablets — box 1',  level: 'casa', sequence: 8 },
      { name: 'Colour Tablets — box 2',  level: 'casa', sequence: 9 },
      { name: 'Colour Tablets — box 3',  level: 'casa', sequence: 10 },
      { name: 'Geometric Solids',        level: 'casa', sequence: 11 },
      { name: 'Geometric Cabinet',       level: 'casa', sequence: 12 },
      { name: 'Binomial Cube',           level: 'casa', sequence: 13 },
      { name: 'Trinomial Cube',          level: 'casa', sequence: 14 },
      { name: 'Tactile Boards',          level: 'casa', sequence: 15 },
      { name: 'Baric Tablets',           level: 'casa', sequence: 16 },
      { name: 'Sound Cylinders',         level: 'casa', sequence: 17 },
      { name: 'Thermic Bottles',         level: 'casa', sequence: 18 },
    ],
  },
  {
    name: 'Mathematics', icon: '🔢', color: '#7C3AED', sequence: 3,
    description: 'Concrete materials that build a natural understanding of numbers and operations',
    activities: [
      { name: 'Number Rods',                      level: 'casa', sequence: 1 },
      { name: 'Sandpaper Numerals (1–9)',          level: 'casa', sequence: 2 },
      { name: 'Number Rods and Cards',             level: 'casa', sequence: 3 },
      { name: 'Spindle Boxes',                     level: 'casa', sequence: 4 },
      { name: 'Cards and Counters',                level: 'casa', sequence: 5 },
      { name: 'Memory Game of Numbers',            level: 'casa', sequence: 6 },
      { name: 'Introduction to Decimal System',    level: 'casa', sequence: 7 },
      { name: 'Formation of Numbers (teens)',      level: 'casa', sequence: 8 },
      { name: 'Formation of Numbers (tens)',       level: 'casa', sequence: 9 },
      { name: 'Stamp Game',                        level: 'casa', sequence: 10 },
      { name: 'Addition — Small Bead Frame',       level: 'casa', sequence: 11 },
      { name: 'Subtraction — Small Bead Frame',    level: 'casa', sequence: 12 },
      { name: 'Addition Snake Game',               level: 'casa', sequence: 13 },
      { name: 'Multiplication Bead Board',         level: 'casa', sequence: 14 },
      { name: 'Division — Bead Board',             level: 'casa', sequence: 15 },
      { name: 'Short Bead Chain — skip counting',  level: 'casa', sequence: 16 },
    ],
  },
  {
    name: 'Language', icon: '📖', color: '#10B981', sequence: 4,
    description: 'Oral language, phonics, writing preparation, and reading',
    activities: [
      { name: 'Oral Language — objects / vocabulary', level: 'casa', sequence: 1 },
      { name: 'Three-Part Cards — nomenclature',      level: 'casa', sequence: 2 },
      { name: 'Metal Insets (writing preparation)',   level: 'casa', sequence: 3 },
      { name: 'Sandpaper Letters — group 1',          level: 'casa', sequence: 4 },
      { name: 'Sandpaper Letters — group 2',          level: 'casa', sequence: 5 },
      { name: 'Sandpaper Letters — group 3',          level: 'casa', sequence: 6 },
      { name: 'Movable Alphabet — phonetic words',    level: 'casa', sequence: 7 },
      { name: 'Movable Alphabet — sentences',         level: 'casa', sequence: 8 },
      { name: 'Object Box — phonetic reading',        level: 'casa', sequence: 9 },
      { name: 'Phonetic Reading — booklets',          level: 'casa', sequence: 10 },
      { name: 'Sight Words',                          level: 'casa', sequence: 11 },
      { name: 'Puzzle Words',                         level: 'casa', sequence: 12 },
      { name: 'Reading Analysis',                     level: 'casa', sequence: 13 },
    ],
  },
  {
    name: 'Cultural', icon: '🌍', color: '#2563EB', sequence: 5,
    description: 'Science, geography, history, art, and music',
    activities: [
      { name: 'Land and Water Forms',                level: 'casa', sequence: 1 },
      { name: 'Globe — land and water',              level: 'casa', sequence: 2 },
      { name: 'Globe — continents (colour)',         level: 'casa', sequence: 3 },
      { name: 'Puzzle Map — World',                  level: 'casa', sequence: 4 },
      { name: 'Puzzle Map — Continent',              level: 'casa', sequence: 5 },
      { name: 'Classified Cards — animals',          level: 'casa', sequence: 6 },
      { name: 'Classified Cards — plants',           level: 'casa', sequence: 7 },
      { name: 'Parts of an Animal (external)',       level: 'casa', sequence: 8 },
      { name: 'Parts of a Plant (root, stem, leaf)', level: 'casa', sequence: 9 },
      { name: 'Life Cycle Cards',                    level: 'casa', sequence: 10 },
      { name: 'Timeline of the Child\'s Life',       level: 'casa', sequence: 11 },
    ],
  },
] as const;
